name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: Gambler13/agor-client
        path: client
    - uses: borales/actions-yarn@v2.0.0
      with:
          cmd: build --mode production --dest ../assets
    - name: Build the Docker image
      run: docker build . --tag my-image-name:$(date +%s)
